### ISSUE TITLE
Rename package to be.swsb, or com.github.softwaresandbox

### ISSUE THREAD

**Issue by Sch3lp** [SoftwareSandbox/KataSkeleton#1]
Instead of package `com.cegeka.kata`.

**Comment by tomjo** [comment]
Done.

**Comment by Sch3lp** [comment]
Noice.

You probably also should've changed the artifactId: https://github.com/SoftwareSandbox/KataSkeleton/blob/master/build.gradle#L8

;)

**Comment by tomjo** [comment]
Guess I was a little too quick ;) Updated now.
